version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev